Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.provision :shell, path: "setup.sh"

    # MQTT
    config.vm.network "public_network"
#    config.vm.network "forwarded_port", guest: 1883, host: 1883
#    config.vm.network "forwarded_port", guest: 15675, host: 15675
#    config.vm.network "forwarded_port", guest: 5353, host: 5353, protocol: "udp"

    config.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 1024
    end
end

